# Generated by Django 3.1.7 on 2021-04-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20210403_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmenu',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
