# Generated by Django 3.1.7 on 2021-04-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20210403_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
    ]
