# Generated by Django 3.1.7 on 2021-04-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_remove_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
