# Generated by Django 3.1.7 on 2021-04-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
