# Generated by Django 3.1.7 on 2021-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20210411_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
